name: Docker Image CI # Actions名称
on: [push] # 执行时机
jobs:

# 这里我使用的是yarn，想用npm的同学将yarn命令修改为npm命令即可
build:
runs-on: ubuntu-latest
steps:
- name: checkout
- uses: actions/checkout@master
# 安装依赖
- name: install
run: yarn
# 打包
- name: build project
run: yarn run build

# 打包镜像推送到阿里云容器镜像服务
- name: Build the Docker image
run: |
docker login --username=healerrr registry.cn-hangzhou.aliyuncs.com --password=ys19940912ysxin2
docker build -t blog:latest .
docker tag blog registry.cn-hangzhou.aliyuncs.com/healerrr/blog:latest
docker push registry.cn-hangzhou.aliyuncs.com/healerrr/blog:latest # 推送
- name: ssh docker login # 使用appleboy/ssh-action@master登录服务器执行拉取镜像脚本，服务器ip、用户名、密码配置方式同容器镜像服务配置方式一样
uses: appleboy/ssh-action@master
with:
host: 47.97.8.179 
username: healerrr
password: ys19940912ysxin2
script: cd ~ && sh blog-deploy.sh healerrr ys19940912ysxin2